# Generated by Django 5.0.6 on 2024-07-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('Specialization', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='doctor')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('ap_date', models.DateField()),
                ('address', models.TextField()),
                ('report', models.FileField(upload_to='patient')),
                ('dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
